---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ec2-instance-action
  title: EC2 Instance Management
  description: Start or stop EC2 instances in your environment.
spec:
  owner: devops
  type: service

  parameters:
    - title: Configuration
      description: Configure the action and environment for your EC2 instance
      properties:
        action:
          title: What would you like to do?
          type: string
          enum:
            - 'start'
            - 'stop'
          enumNames:
            - 'Start Instance'
            - 'Stop Instance'
          default: 'start'
          description: Only instances matching the selected action will be shown.
          ui:autofocus: true
          ui:options:
            rows: 1
        envType:
          title: Environment
          type: string
          enum:
            - 'stage'
            - 'dev'
            - 'qa'
            - 'stress'
          enumNames:
            - 'Stage'
            - 'Development'
            - 'QA'
            - 'Stress'
          default: 'stage'
          description: Select the target environment where the EC2 instance is located
          ui:autofocus: true
          ui:options:
            rows: 1
    - title: Instance Selection
      required:
        - instanceNames
      properties:
        instanceNames:
          title: EC2 Instance Name
          type: string
          description: Select the EC2 instance from the list.
          ui:autofocus: true
          ui:field: SelectFieldFromApi
          ui:options:
            path: 'devops-api/data'
            arraySelector: '.'  # Since your data is a flat object
            valueSelector: 'key'  # Use the key (instance name) as the value
            labelSelector: 'key'  # Show the instance name in the dropdown
            filterBy:
              watchField: 'action'  # Watch the 'action' field
              stateField: 'state'  # Check the 'state' field in each item
              filterMap:
                'stop': 'running'  # When action is 'stop', show only instances with state 'running'
                'start': 'stopped'  # When action is 'start', show only instances with state 'stopped'

  steps:
    - id: backstage_post_request
      name: backstage post request
      action: http:backstage:request
      input:
        method: 'POST'
        path: '/devops-api/${{ parameters.action }}-ec2'
        headers:
          content-type: 'application/json'
        body:
          env: ${{ parameters.envType }}
          instance_names: 
            - ${{ parameters.instanceNames }}

  output:
    postResponse: '{{ steps.backstage_post_request.output.body }}'
    postCode: '{{ steps.backstage_post_request.output.code }}'
    postHeaders: '{{ steps.backstage_post_request.output.headers }}'
