---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ec2-instance-action
  title: EC2 Instance Action
  description: Start or Stop EC2 Instance
spec:
  owner: devops
  type: service

  parameters:
    - title: Action
      properties:
        action:
          title: Action
          type: string
          enum:
            - 'start'
            - 'stop'
          default: 'start'
          description: Choose whether to start or stop the EC2 instance
          ui:autofocus: true
          ui:options:
            rows: 1
    - title: Env Type
      properties:
        envType:
          title: Env Type
          type: string
          enum:
            - 'stage'
            - 'dev'
            - 'qa'
            - 'stress'
          default: 'stage'
          description: The environment type you want to perform the action in
          ui:autofocus: true
          ui:options:
            rows: 1
    - title: EC2 Instance
      properties:
        instanceNames:
          type: string
          ui:autofocus: true
          ui:field: SelectFieldFromApi
          ui:options:
            path: 'devops-api/data'
            arraySelector: '.'  # Since your data is a flat object
            valueSelector: 'key'  # Use the key (instance name) as the value
            labelSelector: 'key'  # Show the instance name in the dropdown
            filterBy:
              watchField: 'action'  # Watch the 'action' field
              stateField: 'state'  # Check the 'state' field in each item
              filterMap:
                'stop': 'running'  # When action is 'stop', show only instances with state 'running'
                'start': 'stopped'  # When action is 'start', show only instances with state 'stopped'

  steps:
    - id: backstage_post_request
      name: backstage post request
      action: http:backstage:request
      input:
        method: 'POST'
        path: '/devops-api/${{ parameters.action }}-ec2'
        headers:
          content-type: 'application/json'
        body:
          env: ${{ parameters.envType }}
          instance_names: 
            - ${{ parameters.instanceNames }}

  output:
    postResponse: '{{ steps.backstage_post_request.output.body }}'
    postCode: '{{ steps.backstage_post_request.output.code }}'
    postHeaders: '{{ steps.backstage_post_request.output.headers }}'

