---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ec2-instance-action
  title: EC2 Instances Action
  description: Start or Stop EC2 Instances
spec:
  owner: devops
  type: service

  parameters:
    - title: Action
      properties:
        action:
          title: Action
          type: string
          enum:
            - 'start'
            - 'stop'
          default: 'start'
          description: Choose whether to start or stop the EC2 instances
          ui:autofocus: true
          ui:options:
            rows: 1
    - title: Env Type
      properties:
        envType:
          title: Env Type
          type: string
          enum:
            - 'stage'
            - 'dev'
            - 'qa'
            - 'stress'
          default: 'stage'
          description: The environment type you want to perform the action in
          ui:autofocus: true
          ui:options:
            rows: 1
    - title: EC2 Instances
      properties:
        instanceNames:
          title: Instance Names
          type: string
          default: 'yoni-devops'
          description: The names of the instances you want to perform the action on
          ui:autofocus: true
          ui:options:
            rows: 1

  steps:
    - id: backstage_post_request
      name: backstage post request
      action: http:backstage:request
      input:
        method: 'POST'
        path: '/devops-api/${{ parameters.action }}-ec2'
        headers:
          content-type: 'application/json'
        body:
          env: ${{ parameters.envType }}
          instance_names: 
            - ${{ parameters.instanceNames }}

  output:
    postResponse: '{{ steps.backstage_post_request.output.body }}'
    postCode: '{{ steps.backstage_post_request.output.code }}'
    postHeaders: '{{ steps.backstage_post_request.output.headers }}'

