---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: HTTP-testing
  title: Http testing for get
  description: Testing get functionality with get
spec:
  owner: roadie
  type: service

  parameters:
    - title: Fill in some params
      properties:
        httpGetPath:
          title: Get Path
          type: string
          description: The path you want to get on your backstage instance
          ui:autofocus: true
          ui:options:
            rows: 5

  steps:
    - id: backstage_request
      name: backstage request
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/devops-api/data'

  output:
    statusCode: '{{ steps.backstage_request.output.code }}'
    responseBody: '{{ steps.backstage_request.output.body }}'
    responseHeaders: '{{ steps.backstage_request.output.headers }}'